//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CxC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class AsientoContable
    {
        [Required(ErrorMessage = " ")]
        public int AsientoID { get; set; }
        [Required(ErrorMessage= " ")]
        public string Descripcion { get; set; }
        [Required(ErrorMessage = " ")]
        public Nullable<int> Id { get; set; }
        [Required(ErrorMessage = " ")]
        public string CuentaContable { get; set; }
        [Required(ErrorMessage = " ")]
        public string TipoMovimiento { get; set; }
        [Required(ErrorMessage = " ")]
        public Nullable<System.DateTime> FechaAsiento { get; set; }
        [Required(ErrorMessage = " ")]
        public Nullable<decimal> MontoAsiento { get; set; }
        [Required(ErrorMessage = " ")]
        public string Estado { get; set; }
    }
}
