//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CxC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Cliente
    {
        [Required(ErrorMessage = " ")]
        public int Id { get; set; }
        [Required(ErrorMessage = " ")]
        public string Nombre { get; set; }
        [Required(ErrorMessage = " ")]
        public string Cedula { get; set; }
        [Required(ErrorMessage = " ")]
        public Nullable<decimal> LimiteCliente { get; set; }
        [Required(ErrorMessage = " ")]
        public string Estado { get; set; }
    }
}
