//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CxC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Transaccion
    {
        [Required(ErrorMessage = " ")]
        public int TansID { get; set; }
        [Required(ErrorMessage = " ")]
        public string Tipo_Movimiento { get; set; }
        [Required(ErrorMessage = " ")]
        public Nullable<int> NumeroDoc { get; set; }
        [Required(ErrorMessage = " ")]
        public Nullable<System.DateTime> FechaTrans { get; set; }
        [Required(ErrorMessage = " ")]
        public Nullable<int> Id { get; set; }
        [Required(ErrorMessage = " ")]
        public Nullable<decimal> Monto { get; set; }
    }
}
